// <auto-generated />
using System;
using InnoGotchi.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InnoGotchi.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230126173853_Update-Eyes")]
    partial class UpdateEyes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Body", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BodyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bodies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "pear_white.png",
                            Name = "White Pear",
                            Type = "pear"
                        },
                        new
                        {
                            Id = 2,
                            FileName = "oval_white.png",
                            Name = "White Oval",
                            Type = "oval"
                        },
                        new
                        {
                            Id = 3,
                            FileName = "square_white.png",
                            Name = "White Square",
                            Type = "square"
                        },
                        new
                        {
                            Id = 4,
                            FileName = "egg_white.png",
                            Name = "White Egg",
                            Type = "egg"
                        },
                        new
                        {
                            Id = 5,
                            FileName = "circle_white.png",
                            Name = "White Circle",
                            Type = "circle"
                        },
                        new
                        {
                            Id = 6,
                            FileName = "pear_black.png",
                            Name = "Black Pear",
                            Type = "pear"
                        },
                        new
                        {
                            Id = 7,
                            FileName = "oval_black.png",
                            Name = "Black Oval",
                            Type = "oval"
                        },
                        new
                        {
                            Id = 8,
                            FileName = "square_black.png",
                            Name = "Black Square",
                            Type = "square"
                        },
                        new
                        {
                            Id = 9,
                            FileName = "egg_black.png",
                            Name = "Black Egg",
                            Type = "egg"
                        },
                        new
                        {
                            Id = 10,
                            FileName = "circle_black.png",
                            Name = "Black Circle",
                            Type = "circle"
                        });
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Eyes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EyesId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Eyes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "eyes_round.png",
                            Name = "Round Eyes"
                        },
                        new
                        {
                            Id = 2,
                            FileName = "eyes_oblong.png",
                            Name = "Oblong Eyes"
                        },
                        new
                        {
                            Id = 3,
                            FileName = "eyes_vertical_oval.png",
                            Name = "Vertical Oval Eyes"
                        },
                        new
                        {
                            Id = 4,
                            FileName = "eyes_vertical_ellipse.png",
                            Name = "Vertical Ellipse Eyes"
                        },
                        new
                        {
                            Id = 5,
                            FileName = "eyes_square.png",
                            Name = "Square Eyes"
                        },
                        new
                        {
                            Id = 6,
                            FileName = "eyes_one.png",
                            Name = "One Eye"
                        },
                        new
                        {
                            Id = 7,
                            FileName = "eyes_tired_oval.png",
                            Name = "Tired Oval Eyes"
                        });
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FarmId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Guests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GuestsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("UserId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Mouth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MouthId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Mouthes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "mouth_cat.png",
                            Name = "Cat Mouth"
                        },
                        new
                        {
                            Id = 2,
                            FileName = "mouth_small_smile.png",
                            Name = "Small Smile"
                        },
                        new
                        {
                            Id = 3,
                            FileName = "mouth_monster.png",
                            Name = "Monster Mouth"
                        },
                        new
                        {
                            Id = 4,
                            FileName = "mouth_monster_libs.png",
                            Name = "Monster Libs"
                        },
                        new
                        {
                            Id = 5,
                            FileName = "mouth_vampire.png",
                            Name = "Vampire Mouth"
                        },
                        new
                        {
                            Id = 6,
                            FileName = "mouth_small_dash.png",
                            Name = "Small Dash"
                        });
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Nose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NoseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Noses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "nose_cat.png",
                            Name = "Cat Nose"
                        },
                        new
                        {
                            Id = 2,
                            FileName = "nose_round.png",
                            Name = "Round Nose"
                        },
                        new
                        {
                            Id = 3,
                            FileName = "nose_anime.png",
                            Name = "Anime Nose"
                        },
                        new
                        {
                            Id = 4,
                            FileName = "nose_egg.png",
                            Name = "Egg Nose"
                        },
                        new
                        {
                            Id = 5,
                            FileName = "nose_sharp.png",
                            Name = "Sharp Nose"
                        });
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Owners", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OwnersId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("UserId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BodyId")
                        .HasColumnType("int");

                    b.Property<int>("EyesId")
                        .HasColumnType("int");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastDrinkTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEatTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastHealthTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMoodTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MouthId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NoseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfCreating")
                        .HasColumnType("datetime2");

                    b.Property<int>("positionX")
                        .HasColumnType("int");

                    b.Property<int>("positionY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatisticsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AlivePetsCount")
                        .HasColumnType("int");

                    b.Property<int>("AverageAge")
                        .HasColumnType("int");

                    b.Property<int>("AverageFeedingPeriod")
                        .HasColumnType("int");

                    b.Property<int>("AverageHappinessPeriod")
                        .HasColumnType("int");

                    b.Property<int>("AverageThirstPeriod")
                        .HasColumnType("int");

                    b.Property<int>("DeadPetsCount")
                        .HasColumnType("int");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsInGame")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMusic")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Guests", b =>
                {
                    b.HasOne("InnoGotchi.API.Entities.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnoGotchi.API.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Owners", b =>
                {
                    b.HasOne("InnoGotchi.API.Entities.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnoGotchi.API.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InnoGotchi.API.Entities.Models.Statistics", b =>
                {
                    b.HasOne("InnoGotchi.API.Entities.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });
#pragma warning restore 612, 618
        }
    }
}
